URL = "https://pacs.printimagem.com.br/login"
USUARIO = "seu_usuario"
SENHA = "sua_senha"

INTERVALO_SEGUNDOS = 15

MODS_ALVO = ["CT", "DX"]

CONVENIOS_ALVO = [
    "CCEST", "POLI-SAUDE", "SAS", "VIZIMED",
    "FUNDAÇÃO SANEPAR", "PARTICULAR", "FISIOMED",
    "ECOVISION", "MEDPREV", "ISSAL",
]

VARREDURA_DURACAO_SEG = 60
VARREDURA_VERIFICACOES = 10

CHECAGEM_DURACAO_SEG = 30
CHECAGEM_MAX_ACOES = 5

REALIZANTE_NOME = "Artur Montemezzo"
